{% set name = "napari-imagej" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 69f1dffc8d39197f09b64e351797f661634f2f718cc999519a7d253cf3901c86

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  number: 0

requirements:
  host:
    - python >=3.8,<=3.11.0
    - setuptools >=61.2
    - pip
  run:
    - python >=3.8,<=3.11.0
    - confuse
    - imglyb >=2.1.0
    - jpype1 >=1.4.1
    - labeling >=0.1.12
    - magicgui >=0.5.1
    - napari >=0.4.17
    - numpy
    - pandas
    - pyimagej >=1.4.1
    - scyjava >=1.8.1
    - qtconsole !=5.4.2
    - typing_extensions !=4.6.0

test:
  imports:
    - napari_imagej
    - napari_imagej.settings

about:
  home: https://github.com/imagej/napari-imagej
  summary: Use ImageJ functionality from napari.
  description: |
    napari-imagej is a napari plugin to access
    ImageJ ecosystem functionality.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://napari-imagej.readthedocs.io/
  dev_url: https://github.com/imagej/napari-imagej

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - gselzer
    - hinerm
