{% set name = "napari-imagej" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: f443049db56d90c9cc79b4a7acfed8b6fcd4b750d43c32899ed62884b871aa88

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vvv --no-deps
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.2
    - pip
  run:
    - python >={{ python_min }},<3.13.0
    - confuse >=2.0.0
    - imglyb >=2.1.0
    - jpype1 >=1.4.1
    - labeling >=0.1.12
    - magicgui >=0.5.1
    - napari >=0.4.17
    - numpy
    - pandas
    - pyimagej >=1.4.1
    - scyjava >=1.9.1
    - superqt >=0.7.0
    - xarray <2024.10.0
    - qtconsole !=5.4.2
    - typing_extensions !=4.6.0

test:
  requires:
    - python {{ python_min }}
  imports:
    - napari_imagej
    - napari_imagej.settings

about:
  home: https://github.com/imagej/napari-imagej
  summary: Use ImageJ functionality from napari.
  description: |
    napari-imagej is a napari plugin to access
    ImageJ ecosystem functionality.
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://napari-imagej.readthedocs.io/
  dev_url: https://github.com/imagej/napari-imagej

extra:
  recipe-maintainers:
    - ctrueden
    - elevans
    - gselzer
    - hinerm
